# Generated by Django 3.2.9 on 2021-11-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SessionConfigItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookie_content', models.TextField(verbose_name='cookie内容')),
                ('source_user', models.CharField(max_length=20, verbose_name='来源用户')),
                ('source_url', models.TextField(verbose_name='来源URL')),
                ('source_title', models.CharField(max_length=100, verbose_name='来源标题')),
                ('source_favicon', models.CharField(max_length=100, verbose_name='来源标题')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
    ]
